Join: '&a&l[&b&l+&a&l] &e%player%'
Leave: '&a&l[&b&l-&a&l] &e%player%'
Messages:
- '&f&l-----------------------------------'
- '&bBienvenido al servidor!'
- '&aBy: &eJkDev'
- '&f&l-----------------------------------'